colors:
  primary: '#0065A1'
  primary_dark: '#005384'
  secondary: '#00B0F0'
  accent: '#FFC700'
  text_dark: '#616161'
  background: '#FFFFFF'
  browser_color: '#FFFFFF'

favicon:
  path: favicon.png

fonts:
  primary:
    fallback: sans-serif
    name: Lato
  secondary:
    fallback: serif
    name: Montserrat
    
google_fonts:
- family: ''
  weights:
  - '200'
  - '400'
  - '700'
- family: Montserrat
  weights:
  - '200'
  - '400'
  - '700'
