colors:
  accent: '#FFC700'
  background: '#FFFFFF'
  browser_color: '#FFFFFF'
  primary: '#0065A1'
  primary_dark: '#005384'
  secondary: '#00B0F0'
  text_dark: '#616161'
favicon:
  path: favicon.png
fonts:
  primary:
    name: trixie.woff
    fallback: sans-serif
  secondary:
    name: trixie.woff
    fallback: serif
