# Please change this by your settings.
info:
  title:
  subtitle:
  description:
  canonical:
  keywords:
  author:

social:
  instagram_url:
  thumbnail:

menu:
  items:
  - label: Home
    href: /

hero:
  # Use gallery.py to automatically add images from config/photos/hero folder
  images: []

footer:
  copyright: Copyright © 2025
  legal_link: '/legals/'
  legal_label: Legal notice

# Build parameters
build:
  theme: modern # choose a theme in config/theme folder

# Change this by your legals
legals:
  hoster_name:
  hoster_adress:
  hoster_contact:
  intellectual_property:
    - paragraph: ""
