info:
  title: ''
  subtitle: ''
  description: ''
  canonical: ''
  keywords: []
  author: ''
social:
  instagram_url: ''
  thumbnail: ''
menu:
  items:
  - label: Home
    href: /
footer:
  copyright: Copyright © 2025
  legal_label: Legal notice
build:
  theme: modern
  convert_images: true
  resize_images: true
legals:
  hoster_name: ''
  hoster_adress: ''
  hoster_contact: ''
  intellectual_property: []
