# Use gallery.py to automatically add photos stored in your /config/photos/gallery folder
# Add tags to your photos as shown below
# remove the # before [] if you removed all images to use gallery.py again

hero:
  images: #[]
    - src: hero/francesco-ungaro-Zbc9Ka8msdI-unsplash.jpg
    - src: hero/gilley-aguilar-ywGDhTlf93E-unsplash.jpg
    - src: hero/jacob-reinikainen-nGG6m3RbjSk-unsplash.jpg

gallery:
  images: #[]
  - src: gallery/almos-bechtold-3402kvtHhOo-unsplash.jpg
    tags: [portrait]
  - src: gallery/arthur-savary-nLfAqmZ2hJo-unsplash.jpg
    tags: [portrait, sunset, boat]
  - src: gallery/francesco-ungaro-Zbc9Ka8msdI-unsplash.jpg
    tags: [landscape, sea, beach, sand]
  - src: gallery/gilley-aguilar-ywGDhTlf93E-unsplash.jpg
    tags: [landscape, sky, cloud, mountains]
  - src: gallery/jacob-reinikainen-nGG6m3RbjSk-unsplash.jpg
    tags: [lanscape, sunset, mountains]
  - src: gallery/jonas-degener-LueP5EdWGFY-unsplash.jpg
    tags: [landscape, mountains, fog]
  - src: gallery/michiel-annaert-M27pZnHV6M0-unsplash.jpg
    tags: [flowers, nature]
  - src: gallery/nir-himi-AjecvkfSHxA-unsplash.jpg
    tags: [landscape, mountains, sky]
  - src: gallery/rachel-mcdermott-0fN7Fxv1eWA-unsplash.jpg
    tags: [portrait, black and white]
  - src: gallery/tianlei-wu-g5o6T-PWT3g-unsplash.jpg
    tags: [cat, animals]
  - src: gallery/we-care-wild-zLweeVLU9Fo-unsplash.jpg
    tags: [bison, animals]
  - src: gallery/y-s-z90w7yStOkk-unsplash.jpg
    tags: [frog, green, animals]
